### ISSUE TITLE
Browserify'd code on upload to Parse.com: ReferenceError: self is not defined

### ISSUE THREAD

**Issue by bartonhammond** [matthew-andrews/isomorphic-fetch#57]
npm command: 
```
 "watchify": "watchify -t babelify src/main.js -o parse/cloud/main.js"
```

When I try to deploy browserify'd code I get:

```
The following files will be uploaded:
/Users/barton/projects/MFV/mapbox/scripts/parse/cloud/main.js
Finished uploading files
ReferenceError: self is not defined
    at main.js:1576:7
    at Object.<anonymous> (main.js:1953:3)
    at s (main.js:1:254)
    at main.js:1:305
    at Object.whatwg-fetch (main.js:1569:1)
    at s (main.js:1:254)
    at main.js:1:305
    at Object../Util (main.js:4282:13)
    at s (main.js:1:254)
    at main.js:1:305
```
main.js 1576:  
```
//
// Return that as the export for use in Webpack, Browserify etc.
require('whatwg-fetch');
module.exports = self.fetch.bind(self);

},{"whatwg-fetch":10}],10:[function(require,module,exports){
(function() {
  'use strict';

  if (self.fetch) {  //<<<<<<<<<< line 1576
    return
  }

```

main.js 1953: self invoking 'whatwg-fetch': 

main.js 1569:   ```require('whatwg-fetch');```

main.js 4282: ```var fetch = require('isomorphic-fetch');```

**Comment by bartonhammond** [comment]
I think I'll just switch to use ```Parse.Cloud.httpRequest```
